# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: hrobot
version: 1.0.0
readme: README.md
authors:
  - Felix Fontein (github.com/felixfontein)
description: Modules for controlling Hetzner's Robot
license_file: COPYING
tags:
  - hetzner
  - robot
  - failover ip
  - firewall
repository: https://github.com/ansible-collections/community.hrobot
documentation: https://ansible.fontein.de/collections/community/hrobot/
#documentation: https://github.com/ansible-collection-migration/community.hrobot/tree/main/docs
homepage: https://github.com/ansible-collections/community.hrobot
issues: https://github.com/ansible-collections/community.hrobot/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
